### ISSUE TITLE
Python 2.6 and portable-ansible-v0.4.2-py2.tar.bz2

### ISSUE THREAD

**Issue by Sinease** [ownport/portable-ansible#19]
I followed the instructions, unpacked the tarball, crested the link and run it as:

python ansible-playbook myTest.yml

This results in stack trace:

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/runpy.py", line 121, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/tmp/ZOX/ansible/__main__.py", line 79, in <module>
    import ansible.constants as C
  File "/tmp/ZOX/ansible/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/tmp/ZOX/ansible/jinja2/__init__.py", line 9, in <module>
    from .bccache import BytecodeCache
  File "/tmp/ZOX/ansible/jinja2/bccache.py", line 24, in <module>
    from .utils import open_if_exists
  File "/tmp/ZOX/ansible/jinja2/utils.py", line 701
    if name in {"_Namespace__attrs", "__class__"}:
    
This test script runs fine in regular ansible.

Any help to make this running?

**Comment by ownport** [comment]
Honestly speaking I don't remember the case when I tested py2.6 and I have plans to remove python 2.x support in coming release. Sorry.
